### ISSUE TITLE
as a NPM package

### ISSUE THREAD

**Issue by antenando** [Datasilk/Selector#1]
Lovely work! Fairly useful.

Any chance this can be published to NPM ?

Many thanks in advance

Keep it up

**Comment by markentingh** [comment]
Sure, I'll publish to NPM, you're very welcome!

Thank you for the encouragement & also for spending time reading the code :) Much appreciated

**Comment by markentingh** [comment]
Here ya go [https://www.npmjs.com/package/selectorjs](https://www.npmjs.com/package/selectorjs)

**Comment by antenando** [comment]
You're the man! 

Many thanks indeed!
